name: Cypress Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      
  schedule:
    - cron: '35 23,11 * * *'
  
jobs:
  cypress-run:
    name: Cypress Tests
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install --force

      - name: Run Cypress Tests
        run: npm run cypress:run

      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          if-no-files-found: ignore # 'warn' or 'error' are also available, defaults to `warn`

      - name: Notify Results
        if: always()
        run: |
          if [ ${{ job.status }} == 'success' ]; then
            echo "Cypress tests passed! :white_check_mark:"
          else
            echo "Cypress tests failed! :x:"
          fi
