name: Cypress Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      
  schedule:
    - cron: '35 23,11 * * *'
  
jobs:
  cypress-run:
    name: Cypress Tests
    runs-on: self-hosted

    env:
      SLACK_WEBHOOK: 'https://hooks.slack.com/services/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'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install --force

      - name: Run Cypress Tests
        run: npm run cypress:run

      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          if-no-files-found: ignore # 'warn' or 'error' are also available, defaults to `warn`
