name: Cypress Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      
  schedule:
    - cron: '35 23,11 * * *'
  
jobs:
  cypress-run:
    name: Cypress Tests
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install --force

      - name: Run Cypress Tests
        run: npm run cypress:run

      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          if-no-files-found: ignore # 'warn' or 'error' are also available, defaults to `warn`

      - name: Send Slack Notification on Success
        if: success()
        uses: slack/notify-action@v2
        with:
          channel: ${{ secrets.SLACK_CHANNEL }}
          message: 'Cypress tests passed! :white_check_mark:'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}

      - name: Send Slack Notification on Failure
        if: failure()
        uses: slack/notify-action@v2
        with:
          channel: ${{ secrets.SLACK_CHANNEL }}
          message: 'Cypress tests failed! :x:'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
