name: Cypress Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      
  schedule:
    - cron: '35 23,11 * * *'
  
jobs:
  cypress-run:
    name: Cypress Tests
    runs-on: self-hosted
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install --force

      - name: Run Cypress Tests
        run: npm run cypress:run

      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          if-no-files-found: ignore # 'warn' or 'error' are also available, defaults to `warn`

      - name: Send Email Notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          from: ${{ secrets.EMAIL_USERNAME }}
          subject: "Notificação do GitHub Actions - Testes Cypress Concluídos"
          body: "Os testes Cypress foram concluídos."
          to: mikaelluizqa@gmail.com

      - name: Discord Webhook Action
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.WEBHOOK_URL }}
          content: "Test"

      - uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ job.status }}
          content: "Hey <@316911818725392384>"
          title: "deploy"
          description: "Build and deploy to GitHub Pages"
          color: 0x0000ff
          url: "https://github.com/sarisia/actions-status-discord"
          username: GitHub Actions
