name: Cypress Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: '35 23,11 * * *'

jobs:
  cypress-run:
    name: Cypress Tests
    runs-on: self-hosted
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install --force

      - name: Run Cypress Tests
        run: npm run cypress:run

      - name: Upload Screenshots on Failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          if-no-files-found: ignore # 'warn' or 'error' are also available, defaults to `warn`

      - name: Send Email Notification on Failure
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          from: ${{ secrets.EMAIL_USERNAME }}
          subject: "Notificação do GitHub Actions - Testes Cypress Falharam"
          body: |
            <html>
            <body>
              <p>Olá,</p>
              <p>Gostaríamos de informar que os testes Cypress falharam. Anexamos as capturas de tela para sua referência.</p>
              <p>Atenciosamente,<br/>Sua equipe de testes</p>
            </body>
            </html>
          to: mikaelluizqa@gmail.com

      - name: Send Email Notification on Success
        if: success()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          from: ${{ secrets.EMAIL_USERNAME }}
          subject: "Notificação do GitHub Actions - Testes Cypress Concluídos"
          body: |
            <html>
            <body>
              <p>Olá,</p>
              <p>Gostaríamos de informar que os testes Cypress foram concluídos com sucesso. Você pode ver os detalhes do workflow <a href="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}">aqui</a>.</p>
              <p>Atenciosamente,<br/>Sua equipe de testes</p>
            </body>
            </html>
          to: mikaelluizqa@gmail.com


      - uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ job.status }}
          content: "Hey <@316911818725392384>"
          title: "deploy"
          description: "Build and deploy to GitHub Pages"
          color: 0x0000ff
          url: "https://github.com/sarisia/actions-status-discord"
          username: GitHub Actions
