name: Cypress Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: '35 23,11 * * *'

jobs:
  cypress-run:
    name: Cypress Tests
    runs-on: self-hosted
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install --force

      - name: Run Cypress Tests
        run: npm run cypress:run

      - name: Upload Screenshots on Failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          if-no-files-found: ignore # 'warn' or 'error' are also available, defaults to `warn`

      - name: Enviar Notificação por E-mail em Caso de Sucesso
        if: success()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          from: ${{ secrets.EMAIL_USERNAME }}
          subject: "Notificação - Testes Cypress Concluídos"
          body: |
            Olá,
      
            Gostaríamos de informar que os testes Cypress foram concluídos com sucesso.
      
            Atenciosamente,
            [Time de QA]
          to: mikaelluizqa@gmail.com

      - uses: sarisia/actions-status-discord@v1
        if: failure()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ job.status }}
          content: "Hey Time!!"
          title: ${{ github.workflow}}
          description: "Testes Automatizados: Falhou!"
          color: 0xff0000
          url: "https://esolution.com.br/"
          username: Cypress eSolution
          image: ${{ secrets.EMBED_IMAGE }}0

      - uses: sarisia/actions-status-discord@v1
        if: success()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ job.status }}
          content: "Hey Time!!"
          title: ${{ github.workflow}}
          description: "Testes Automatizados: Sucesso!"
          color: 0x0000ff
          url: "https://esolution.com.br/"
          username: Cypress eSolution
          image: ${{ secrets.EMBED_IMAGE }}
